services:
  postgis:
    image: postgis/postgis:latest
    # container_name: postgis-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    networks:
      - db_network
    command: -c config_file=/etc/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    networks:
      - db_network
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgis
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 5


  # DOES NOT WORK SINCE 
  osm2pgsql:
    image: iboates/osm2pgsql
    depends_on:
      postgis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGHOST: ${POSTGRES_HOST}
    volumes:
      - ./data:/data:ro
      - ./osm2pgsql/style.lua:/style.lua:ro
    networks:
      - db_network
    command: 
      - "--slim"
      - "--cache=${OSM2PGSQL_CACHE}"
      - "--output"
      - "flex"
      - "--style"
      - "/style.lua"
      - "--number-processes"
      - "4"
      - "/data/map.osm.pbf"
    restart: "on-failure"


  tippecanoe:
    build:
      dockerfile: Dockerfile
      context: ./data/tippecanoe
    volumes:
      - ./data:/data
      - ./static_srv:/output
    command: "tippecanoe -o /output/water_polygons.mbtiles --force -z14 -Z0 --cluster-densest-as-needed --coalesce /data/water-polygons-split-3857/water_polygons.shp"


  shp2pgsql:
    image: postgis/postgis:latest
    depends_on:
      postgis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/data
    networks:
      - db_network
    command: shp2pgsql -I -s ${OSM2PGSQL_SRID} /data/water-polygons-split-small/water.shp water_small


  # pyosmium:
  #   image: osmcode/pyosmium
  #   container_name: pyosmium-updater
  #   volumes:
  #     - ./data:/data
  #   command: "pyosmium-up-to-date -d /data"
  #   depends_on:
  #     - postgis
  #   restart: always
  #   environment:
  #     OSM_API_URL: ${OSM_API_URL}
  #   healthcheck:
  #     test: ["CMD", "test", "-f", "/data/last.state.txt"]
  #     interval: 5m
  #     timeout: 10s
  #     retries: 5


  martin:
    image: ghcr.io/maplibre/martin
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgis
    volumes:
      - ./martin.yaml:/config/martin.yaml:ro
      - ./sprites:/sprites
      - ./data:/data
    networks:
      - db_network
      - tile_server_network
    command: ["--config", "/config/martin.yaml"]


  nginx:
    image: nginx:alpine
    depends_on:
      - martin
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - cache:/var/cache/nginx
    networks:
      - tile_server_network


  maputnik:
    image: ghcr.io/maplibre/maputnik:main
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - ./style.json:/data/style.json
    depends_on:
      - nginx
    networks:
      - tile_server_network
    # command: ["--watch", "--file", "/data/style.json"]


volumes:
  pgdata:
  pgadmin:
  cache:


networks:
  db_network:
  tile_server_network:
  # cache_network:
  # web:
  #   external: true
